### ISSUE TITLE
The node merge_handler is not starting

### ISSUE THREAD

**Issue by AshayAswale** [NESTLab/coms#22]
This line from file `coms/coms/src/mapmerge/ros_utils.py` is giving me error, last commit by @nikopoulospet 
```py
    img[img >= 250] = FREE # temp
```

Last relevant commit info:
> nikopoulospet, last month   (February 10th, 2022 8:46pm) 
> Ros nodes (#3)
> Add support for merging ROS nodes

Full error log:
```
[ WARN:0@0.299] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/root/catkin_ws/src/coms/testData/map_part0.pgm'): can't open/read file: check file path/integrity
INVALID FILENAME /root/catkin_ws/src/coms/testData/map_part0.pgm
Traceback (most recent call last):
  File "/root/catkin_ws/src/coms/coms/src/nodes/merge_handler.py", line 65, in <module>
    MH = MergeHandler()
  File "/root/catkin_ws/src/coms/coms/src/nodes/merge_handler.py", line 19, in __init__
    self.latest_map = pgm_to_numpy(self.data_path + "/map_part0.pgm")
  File "/root/catkin_ws/src/coms/coms/src/mapmerge/ros_utils.py", line 37, in pgm_to_numpy
    img[img >= 250] = FREE # temp
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
[merge_handler-2] process has died [pid 16635, exit code 1, cmd /root/catkin_ws/src/coms/coms/src/nodes/merge_handler.py __name:=merge_handler __log:=/root/.ros/log/eeb6a65a-a471-11ec-a568-0242ac150002/merge_handler-2.log].
log file: /root/.ros/log/eeb6a65a-a471-11ec-a568-0242ac150002/merge_handler-2*.log
```

**Comment by nikopoulospet** [comment]
What branch is this?

Also adding Connor because this is his utils method @cj-mclaughlin

**Comment by cj-mclaughlin** [comment]
Looks like the map filepath is incorrect, as reading from it returns `None`.

**Comment by AshayAswale** [comment]
The branch is `main`, commit ed198c7 

@cj-mclaughlin I didn't fix anything yet, the filepath is hardcoded in the code. Can you push those files such that it may no longer be the issue?

Also, why are we using the `testData` for the actual code? Or am I launching a file that is not supposed to be launched?

**Comment by cj-mclaughlin** [comment]
That looks like a mistake, the merge handler shouldn't be using the static paths but rather reading the local map from the rostopic and the foreign maps from the coms.

**Comment by nikopoulospet** [comment]
Running on add-state-machine gives you a more up to date merge handler with the test map loading removed

**Comment by AshayAswale** [comment]
Can you elaborate? am I launching incorrect node?

It wasn't being launched by default, I found that this node was the only node starting the rosservice `/<robot_name>/merge` which is referred by the state machine `MEET` state. Was that right?
